//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RowaWcf.Tests.ServiceNetTcp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNetTcp.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoAction", ReplyAction="http://tempuri.org/ITestService/DoActionResponse")]
        void DoAction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoAction", ReplyAction="http://tempuri.org/ITestService/DoActionResponse")]
        System.Threading.Tasks.Task DoActionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/GetMyEndpoint", ReplyAction="http://tempuri.org/ITestService/GetMyEndpointResponse")]
        string GetMyEndpoint();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/GetMyEndpoint", ReplyAction="http://tempuri.org/ITestService/GetMyEndpointResponse")]
        System.Threading.Tasks.Task<string> GetMyEndpointAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : RowaWcf.Tests.ServiceNetTcp.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<RowaWcf.Tests.ServiceNetTcp.ITestService>, RowaWcf.Tests.ServiceNetTcp.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoAction() {
            base.Channel.DoAction();
        }
        
        public System.Threading.Tasks.Task DoActionAsync() {
            return base.Channel.DoActionAsync();
        }
        
        public string GetMyEndpoint() {
            return base.Channel.GetMyEndpoint();
        }
        
        public System.Threading.Tasks.Task<string> GetMyEndpointAsync() {
            return base.Channel.GetMyEndpointAsync();
        }
    }
}
